# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('medBSA_rcpparma_hello_world', PACKAGE = 'medBSA')
}

rcpparma_outerproduct <- function(x) {
    .Call('medBSA_rcpparma_outerproduct', PACKAGE = 'medBSA', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('medBSA_rcpparma_innerproduct', PACKAGE = 'medBSA', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('medBSA_rcpparma_bothproducts', PACKAGE = 'medBSA', x)
}

#' Select elements from a matrix based on a vector of column indices
#'
#' From a matrix and a vector, return a vector where the ith element is the
#' matrix element (i, v[i])
#'
#' Faster version of M[cbind(1:length(v), v)]
#'
#' @param M The n by m matrix
#' @param v The length-n vector taking integer values 1 to m
column_picker <- function(M, v) {
    .Call('medBSA_column_pickerCpp', PACKAGE = 'medBSA', M, v)
}

normalize_rows <- function(M) {
    .Call('medBSA_normalize_rowsCpp', PACKAGE = 'medBSA', M)
}

getbcl <- function(design_mat, coef_mat) {
    .Call('medBSA_getbcl', PACKAGE = 'medBSA', design_mat, coef_mat)
}

expit <- function(x) {
    .Call('medBSA_expit_double', PACKAGE = 'medBSA', x)
}

ll_logisticReg <- function(out_v, coef_v, des_m) {
    .Call('medBSA_ll_logisticReg', PACKAGE = 'medBSA', out_v, coef_v, des_m)
}

dU <- function(coef_U, Z, A, U, lg) {
    .Call('medBSA_dU_Cpp', PACKAGE = 'medBSA', coef_U, Z, A, U, lg)
}

dY <- function(coef_Y, Z, A, asmM, U, Y, intx, lg) {
    .Call('medBSA_dY_Cpp', PACKAGE = 'medBSA', coef_Y, Z, A, asmM, U, Y, intx, lg)
}

dM <- function(coef_M, Z, A, U, asmM, M, lg) {
    .Call('medBSA_dM_Cpp', PACKAGE = 'medBSA', coef_M, Z, A, U, asmM, M, lg)
}

get_pU1 <- function(Z, Y, A, asmM, M, coef_M, coef_Y, coef_U) {
    .Call('medBSA_get_pU1_Cpp', PACKAGE = 'medBSA', Z, Y, A, asmM, M, coef_M, coef_Y, coef_U)
}

calc_ARD <- function(coef_M, Z, U, coef_Y, intx) {
    .Call('medBSA_calc_ARD_Cpp', PACKAGE = 'medBSA', coef_M, Z, U, coef_Y, intx)
}

